import type { Consumable } from "../schemas"

export const consumables: Consumable[] = [
  {
    id: "consumable:strength_elixir",
    entityType: "consumable",
    name: "Strength Elixir",
    type: "consumable",
    value: 30,
    rarity: "uncommon",
    icon: "ra-flask",
    consumableEffect: {
      type: "temporary",
      duration: 120,
      statChanges: { attack: 50 },
      scope: "global",
    },
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["buff", "attack", "temporary"],
  },
  {
    id: "consumable:iron_skin_potion",
    entityType: "consumable",
    name: "Iron Skin Potion",
    type: "consumable",
    value: 25,
    rarity: "uncommon",
    icon: "ra-bottle-vapors",
    consumableEffect: {
      type: "temporary",
      duration: 90,
      statChanges: { defense: 30 },
      scope: "global",
    },
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["buff", "defense", "temporary"],
  },
  {
    id: "consumable:berserker_brew",
    entityType: "consumable",
    name: "Berserker Brew",
    type: "consumable",
    value: 50,
    rarity: "rare",
    icon: "ra-bubbling-potion",
    consumableEffect: {
      type: "temporary",
      duration: 60,
      statChanges: { attack: 100, defense: -20 },
      scope: "global",
    },
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["buff", "risk", "temporary"],
  },
  {
    id: "consumable:titans_blessing",
    entityType: "consumable",
    name: "Titan's Blessing",
    type: "consumable",
    value: 80,
    rarity: "epic",
    icon: "ra-vial",
    consumableEffect: {
      type: "temporary",
      duration: 180,
      statChanges: { attack: 75, defense: 50 },
      scope: "global",
    },
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["buff", "powerful", "temporary"],
  },
  {
    id: "consumable:permanent_strength_tome",
    entityType: "consumable",
    name: "Permanent Strength Tome",
    type: "consumable",
    value: 100,
    rarity: "legendary",
    icon: "ra-book",
    consumableEffect: {
      type: "permanent",
      statChanges: { attack: 10 },
      scope: "global",
    },
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["permanent", "attack", "rare"],
  },
  {
    id: "consumable:permanent_defense_scroll",
    entityType: "consumable",
    name: "Permanent Defense Scroll",
    type: "consumable",
    value: 100,
    rarity: "legendary",
    icon: "ra-scroll-unfurled",
    consumableEffect: {
      type: "permanent",
      statChanges: { defense: 8 },
      scope: "global",
    },
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["permanent", "defense", "rare"],
  },
]
