import type { Consumable } from "../schemas"

export const consumables: Consumable[] = [
  {
    id: "consumable:strength_elixir",
    entityType: "consumable",
    name: "Strength Elixir",
    type: "consumable",
    value: 30,
    rarity: "uncommon",
    icon: "ra-flask",
    consumableEffect: {
      type: "temporary",
      duration: 120,
      statChanges: { attack: 50 },
      scope: "global",
    },
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["buff", "attack", "temporary"],
  },
  {
    id: "consumable:iron_skin_potion",
    entityType: "consumable",
    name: "Iron Skin Potion",
    type: "consumable",
    value: 25,
    rarity: "uncommon",
    icon: "ra-bottle-vapors",
    consumableEffect: {
      type: "temporary",
      duration: 90,
      statChanges: { defense: 30 },
      scope: "global",
    },
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["buff", "defense", "temporary"],
  },
  {
    id: "consumable:berserker_brew",
    entityType: "consumable",
    name: "Berserker Brew",
    type: "consumable",
    value: 50,
    rarity: "rare",
    icon: "ra-bubbling-potion",
    consumableEffect: {
      type: "temporary",
      duration: 60,
      statChanges: { attack: 100, defense: -20 },
      scope: "global",
    },
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["buff", "risk", "temporary"],
  },
  {
    id: "consumable:titans_blessing",
    entityType: "consumable",
    name: "Titan's Blessing",
    type: "consumable",
    value: 80,
    rarity: "epic",
    icon: "ra-vial",
    consumableEffect: {
      type: "temporary",
      duration: 180,
      statChanges: { attack: 75, defense: 50 },
      scope: "global",
    },
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["buff", "powerful", "temporary"],
  },
  {
    id: "consumable:permanent_strength_tome",
    entityType: "consumable",
    name: "Permanent Strength Tome",
    type: "consumable",
    value: 100,
    rarity: "legendary",
    icon: "ra-book",
    consumableEffect: {
      type: "permanent",
      statChanges: { attack: 10 },
      scope: "global",
    },
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["permanent", "attack", "rare"],
  },
  {
    id: "consumable:permanent_defense_scroll",
    entityType: "consumable",
    name: "Permanent Defense Scroll",
    type: "consumable",
    value: 100,
    rarity: "legendary",
    icon: "ra-scroll-unfurled",
    consumableEffect: {
      type: "permanent",
      statChanges: { defense: 8 },
      scope: "global",
    },
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["permanent", "defense", "rare"],
  },
  {
    id: "consumable:portal_anchor",
    entityType: "consumable",
    name: "Portal Anchor",
    type: "consumable",
    value: 50,
    rarity: "rare",
    icon: "ra-anchor",
    consumableEffect: {
      type: "temporary",
      duration: 999999,
      statChanges: {},
      scope: "portal",
    },
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["portal", "stability", "buff"],
    description: "Reduces portal stability decay by 15%. Active only in current portal.",
  },
  {
    id: "consumable:dimensional_ward",
    entityType: "consumable",
    name: "Dimensional Ward",
    type: "consumable",
    value: 45,
    rarity: "rare",
    icon: "ra-tower-shield",
    consumableEffect: {
      type: "temporary",
      duration: 999999,
      statChanges: { defense: 20 },
      scope: "portal",
    },
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["portal", "defense", "buff"],
    description: "Grants +20 defense while in portals. Active only in current portal.",
  },
  {
    id: "consumable:explorers_blessing",
    entityType: "consumable",
    name: "Explorer's Blessing",
    type: "consumable",
    value: 30,
    rarity: "uncommon",
    icon: "ra-compass",
    consumableEffect: {
      type: "temporary",
      duration: 999999,
      statChanges: { attack: 5 },
      scope: "portal",
    },
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["portal", "attack", "buff"],
    description: "Grants +5 attack while exploring portals. Active only in current portal.",
  },
  {
    id: "consumable:cavern_blessing",
    entityType: "consumable",
    name: "Cavern Blessing",
    type: "consumable",
    value: 75,
    rarity: "epic",
    icon: "ra-crystals",
    consumableEffect: {
      type: "temporary",
      duration: 999999,
      statChanges: {},
      scope: "portal",
    },
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["portal", "stability", "buff", "epic"],
    description: "Reduces portal stability decay by 20%. Active only in current portal.",
  },
  {
    id: "consumable:portal_resilience",
    entityType: "consumable",
    name: "Portal Resilience",
    type: "consumable",
    value: 35,
    rarity: "uncommon",
    icon: "ra-health",
    consumableEffect: {
      type: "temporary",
      duration: 999999,
      statChanges: { health: 15 },
      scope: "portal",
    },
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["portal", "health", "buff"],
    description: "Grants +15 health while in portals. Active only in current portal.",
  },
]
