import type { Enemy } from "../schemas"

export const enemies: Enemy[] = [
  {
    id: "enemy:goblin",
    entityType: "enemy",
    name: "Goblin",
    health: 20,
    attack: 5,
    gold: 10,
    exp: 15,
    rarity: "common",
    icon: "ra-monster-skull",
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["melee", "weak"],
  },
  {
    id: "enemy:skeleton",
    entityType: "enemy",
    name: "Skeleton",
    health: 30,
    attack: 8,
    gold: 15,
    exp: 20,
    rarity: "common",
    icon: "ra-skull",
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["undead", "melee"],
  },
  {
    id: "enemy:orc",
    entityType: "enemy",
    name: "Orc",
    health: 40,
    attack: 12,
    gold: 25,
    exp: 30,
    rarity: "uncommon",
    icon: "ra-monster-skull",
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["melee", "strong"],
  },
  {
    id: "enemy:dark_knight",
    entityType: "enemy",
    name: "Dark Knight",
    health: 60,
    attack: 15,
    gold: 50,
    exp: 50,
    rarity: "rare",
    icon: "ra-knight-helmet",
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["armored", "melee"],
  },
  {
    id: "enemy:shadow_demon",
    entityType: "enemy",
    name: "Shadow Demon",
    health: 80,
    attack: 20,
    gold: 75,
    exp: 70,
    rarity: "epic",
    icon: "ra-death-skull",
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["demon", "magic"],
    color: "text-violet-400", // Custom demon color
  },
  {
    id: "enemy:ancient_dragon",
    entityType: "enemy",
    name: "Ancient Dragon",
    health: 120,
    attack: 30,
    gold: 150,
    exp: 100,
    rarity: "legendary",
    icon: "ra-dragon-head",
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["dragon", "boss", "fire"],
    color: "text-red-500", // Custom boss/dragon color (fire theme)
  },
  // Fire-themed enemies
  {
    id: "enemy:flame_imp",
    entityType: "enemy",
    name: "Flame Imp",
    health: 25,
    attack: 7,
    gold: 12,
    exp: 18,
    rarity: "common",
    icon: "ra-fire",
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["fire", "demon", "elemental"],
    color: "text-orange-500",
  },
  {
    id: "enemy:inferno_knight",
    entityType: "enemy",
    name: "Inferno Knight",
    health: 55,
    attack: 18,
    gold: 45,
    exp: 55,
    rarity: "rare",
    icon: "ra-burning-embers",
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["fire", "armored", "elemental"],
    color: "text-red-500",
  },
  // Ice-themed enemies
  {
    id: "enemy:frost_sprite",
    entityType: "enemy",
    name: "Frost Sprite",
    health: 22,
    attack: 6,
    gold: 11,
    exp: 16,
    rarity: "common",
    icon: "ra-crystals",
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["ice", "elemental", "magic"],
    color: "text-cyan-400",
  },
  {
    id: "enemy:ice_wraith",
    entityType: "enemy",
    name: "Ice Wraith",
    health: 50,
    attack: 14,
    gold: 40,
    exp: 48,
    rarity: "rare",
    icon: "ra-snowflake",
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["ice", "undead", "elemental"],
    color: "text-blue-300",
  },
  {
    id: "enemy:glacial_titan",
    entityType: "enemy",
    name: "Glacial Titan",
    health: 95,
    attack: 24,
    gold: 85,
    exp: 75,
    rarity: "epic",
    icon: "ra-ice-cube",
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["ice", "giant", "elemental", "boss"],
    color: "text-cyan-300",
  },
  // Poison-themed enemies
  {
    id: "enemy:toxic_slime",
    entityType: "enemy",
    name: "Toxic Slime",
    health: 28,
    attack: 9,
    gold: 14,
    exp: 20,
    rarity: "uncommon",
    icon: "ra-droplet",
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["poison", "blob", "elemental"],
    color: "text-green-500",
  },
  {
    id: "enemy:venom_spider",
    entityType: "enemy",
    name: "Venom Spider",
    health: 35,
    attack: 11,
    gold: 22,
    exp: 28,
    rarity: "uncommon",
    icon: "ra-web",
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["poison", "beast", "fast"],
    color: "text-lime-500",
  },
  {
    id: "enemy:plague_bearer",
    entityType: "enemy",
    name: "Plague Bearer",
    health: 65,
    attack: 19,
    gold: 55,
    exp: 58,
    rarity: "rare",
    icon: "ra-death-skull",
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["poison", "undead", "disease"],
    color: "text-green-600",
  },
  // Void-themed enemies
  {
    id: "enemy:void_spawn",
    entityType: "enemy",
    name: "Void Spawn",
    health: 32,
    attack: 10,
    gold: 18,
    exp: 25,
    rarity: "uncommon",
    icon: "ra-tentacle",
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["void", "aberration", "cosmic"],
    color: "text-purple-500",
  },
  {
    id: "enemy:void_stalker",
    entityType: "enemy",
    name: "Void Stalker",
    health: 70,
    attack: 22,
    gold: 65,
    exp: 68,
    rarity: "epic",
    icon: "ra-eyeball",
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["void", "aberration", "stealth"],
    color: "text-violet-400",
  },
  {
    id: "enemy:void_horror",
    entityType: "enemy",
    name: "Void Horror",
    health: 110,
    attack: 28,
    gold: 130,
    exp: 95,
    rarity: "legendary",
    icon: "ra-monster-skull",
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["void", "aberration", "boss", "cosmic"],
    color: "text-purple-600",
  },
]
