import type { MapItem } from "../schemas"

export const maps: MapItem[] = [
  {
    id: "map:crumbling_map",
    entityType: "map",
    name: "Crumbling Map",
    locationName: "Forgotten Catacombs",
    entrances: 2,
    rarity: "common",
    value: 15,
    icon: "ra-scroll-unfurled",
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["location", "portal"],
    portalMetadata: {
      expectedRoomCount: 4,
      stabilityDecayRate: { min: 5, max: 15 },
      eventDiversity: ["combat", "treasure", "mystery"],
      riskLevel: "low",
      theme:
        "Forgotten Catacombs - crumbling stone passages, undead presence, ancient burial chambers",
    },
  },
  {
    id: "map:weathered_map",
    entityType: "map",
    name: "Weathered Map",
    locationName: "Ancient Library",
    entrances: 3,
    rarity: "uncommon",
    value: 25,
    icon: "ra-scroll-unfurled",
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["location", "portal"],
    portalMetadata: {
      expectedRoomCount: 6,
      stabilityDecayRate: { min: 8, max: 18 },
      eventDiversity: ["mystery", "treasure", "combat"],
      riskLevel: "medium",
      theme:
        "Ancient Library - dusty tomes, arcane knowledge, guardian constructs, forgotten secrets",
      themeColor: "text-amber-500",
    },
  },
  {
    id: "map:enchanted_map",
    entityType: "map",
    name: "Enchanted Map",
    locationName: "Crystal Caverns",
    entrances: 4,
    rarity: "rare",
    value: 40,
    icon: "ra-compass",
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["location", "portal", "magic"],
    portalMetadata: {
      expectedRoomCount: 8,
      stabilityDecayRate: { min: 10, max: 20 },
      eventDiversity: ["combat", "treasure", "mystery", "hazard"],
      riskLevel: "high",
      theme:
        "Crystal Caverns - luminous crystal formations, arcane energy, elemental hazards, magical resonance",
      themeColor: "text-cyan-400",
    },
  },
  {
    id: "map:mystical_map",
    entityType: "map",
    name: "Mystical Map",
    locationName: "Dragon's Lair",
    entrances: 5,
    rarity: "legendary",
    value: 60,
    icon: "ra-compass",
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["location", "portal", "dragon"],
    portalMetadata: {
      expectedRoomCount: 13,
      stabilityDecayRate: { min: 12, max: 25 },
      eventDiversity: ["combat", "treasure", "mystery", "hazard", "rest"],
      riskLevel: "extreme",
      theme:
        "Dragon's Lair - scorched chambers, hoarded treasures, draconic guardians, volcanic hazards",
      themeColor: "text-red-500",
    },
  },
  {
    id: "map:torn_map",
    entityType: "map",
    name: "Torn Map",
    locationName: "Abandoned Mine",
    entrances: 2,
    rarity: "common",
    value: 12,
    icon: "ra-scroll-unfurled",
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["location", "portal"],
    portalMetadata: {
      expectedRoomCount: 3,
      stabilityDecayRate: { min: 5, max: 15 },
      eventDiversity: ["combat", "hazard", "treasure"],
      riskLevel: "low",
      theme: "Abandoned Mine - dark tunnels, cave-ins, mining equipment, lurking creatures",
    },
  },
  {
    id: "map:ancient_map",
    entityType: "map",
    name: "Ancient Map",
    locationName: "Sunken Temple",
    entrances: 3,
    rarity: "uncommon",
    value: 30,
    icon: "ra-scroll-unfurled",
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["location", "portal", "ancient"],
    portalMetadata: {
      expectedRoomCount: 6,
      stabilityDecayRate: { min: 8, max: 18 },
      eventDiversity: ["mystery", "hazard", "combat", "treasure"],
      riskLevel: "medium",
      theme:
        "Sunken Temple - flooded chambers, ancient rituals, water hazards, corrupted guardians",
      themeColor: "text-blue-400",
    },
  },
]
