import type { MapItem } from "../schemas"

export const maps: MapItem[] = [
  {
    id: "map:crumbling_map",
    entityType: "map",
    name: "Crumbling Map",
    locationName: "Forgotten Catacombs",
    entrances: 2,
    rarity: "common",
    value: 15,
    icon: "ra-scroll-unfurled",
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["location", "portal"],
  },
  {
    id: "map:weathered_map",
    entityType: "map",
    name: "Weathered Map",
    locationName: "Ancient Library",
    entrances: 3,
    rarity: "uncommon",
    value: 25,
    icon: "ra-scroll-unfurled",
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["location", "portal"],
  },
  {
    id: "map:enchanted_map",
    entityType: "map",
    name: "Enchanted Map",
    locationName: "Crystal Caverns",
    entrances: 4,
    rarity: "rare",
    value: 40,
    icon: "ra-compass",
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["location", "portal", "magic"],
  },
  {
    id: "map:mystical_map",
    entityType: "map",
    name: "Mystical Map",
    locationName: "Dragon's Lair",
    entrances: 5,
    rarity: "legendary",
    value: 60,
    icon: "ra-compass",
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["location", "portal", "dragon"],
  },
  {
    id: "map:torn_map",
    entityType: "map",
    name: "Torn Map",
    locationName: "Abandoned Mine",
    entrances: 2,
    rarity: "common",
    value: 12,
    icon: "ra-scroll-unfurled",
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["location", "portal"],
  },
  {
    id: "map:ancient_map",
    entityType: "map",
    name: "Ancient Map",
    locationName: "Sunken Temple",
    entrances: 3,
    rarity: "uncommon",
    value: 30,
    icon: "ra-scroll-unfurled",
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["location", "portal", "ancient"],
  },
]
