import type { Treasure } from "../schemas"

export const treasures: Treasure[] = [
  {
    id: "treasure:health_potion",
    entityType: "treasure",
    name: "Health Potion",
    type: "potion",
    value: 20,
    rarity: "common",
    icon: "ra-potion",
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["healing", "consumable"],
  },
  {
    id: "treasure:steel_sword",
    entityType: "treasure",
    name: "Steel Sword",
    type: "weapon",
    value: 15,
    stats: { attack: 8 },
    rarity: "uncommon",
    icon: "ra-sword",
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["weapon", "melee"],
  },
  {
    id: "treasure:iron_shield",
    entityType: "treasure",
    name: "Iron Shield",
    type: "armor",
    value: 10,
    stats: { defense: 6 },
    rarity: "uncommon",
    icon: "ra-shield",
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["armor", "defense"],
  },
  {
    id: "treasure:gold_coins",
    entityType: "treasure",
    name: "Gold Coins",
    type: "treasure",
    value: 30,
    rarity: "common",
    icon: "ra-gold-bar",
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["currency"],
  },
  {
    id: "treasure:ancient_amulet",
    entityType: "treasure",
    name: "Ancient Amulet",
    type: "accessory",
    value: 50,
    stats: { attack: 3, defense: 3 },
    rarity: "rare",
    icon: "ra-gem-pendant",
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["accessory", "balanced"],
  },
  {
    id: "treasure:dragon_blade",
    entityType: "treasure",
    name: "Dragon Blade",
    type: "weapon",
    value: 40,
    stats: { attack: 15 },
    rarity: "epic",
    icon: "ra-fire-sword",
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["weapon", "fire", "powerful"],
  },
  {
    id: "treasure:plate_armor",
    entityType: "treasure",
    name: "Plate Armor",
    type: "armor",
    value: 35,
    stats: { defense: 12 },
    rarity: "rare",
    icon: "ra-shield",
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["armor", "heavy"],
  },
  {
    id: "treasure:ring_of_vitality",
    entityType: "treasure",
    name: "Ring of Vitality",
    type: "accessory",
    value: 25,
    stats: { health: 20 },
    rarity: "uncommon",
    icon: "ra-gem-pendant",
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["accessory", "health"],
  },
  {
    id: "treasure:legendary_excalibur",
    entityType: "treasure",
    name: "Legendary Excalibur",
    type: "weapon",
    value: 100,
    stats: { attack: 25 },
    rarity: "legendary",
    icon: "ra-sword",
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["weapon", "legendary", "holy"],
  },
  {
    id: "treasure:mythril_armor",
    entityType: "treasure",
    name: "Mythril Armor",
    type: "armor",
    value: 80,
    stats: { defense: 20 },
    rarity: "epic",
    icon: "ra-shield",
    source: "canonical",
    version: 1,
    sessionOnly: false,
    tags: ["armor", "mythril", "powerful"],
  },
]
